<table class="form">
    <tr>
        <td colspan="2"><textarea name="body" rows="20" cols="100" id="body"></textarea></td>
    </tr>
    <tr>
        <th>タグ</th>
        <td><input type="text" name="tags" size="80"></td>
    </tr>
    <tr>
        <td colspan="2"><input type="checkbox" name="publish_blog" value="1" /> Blog公開する</td>
    </tr>
    <tr>
        <td colspan="2"><input type="submit" value="更新" /></td>
    </tr>
</table>
